"""Export the current application and locally built artifacts for Docker Spaces."""

import argparse
import hashlib
import json
import shutil
from pathlib import Path


PROJECT_DIR = Path(__file__).resolve().parents[1]
EXPORT_FILES = (
    "api.py",
    "retrieval.py",
    "requirements-baseline.txt",
    "requirements-web.txt",
    "web/index.html",
    "web/style.css",
    "web/app.js",
    "models/question_classifier.joblib",
    "models/retrieval_index.joblib",
    "DATA_SOURCES.md",
    "data/medquad_revision.txt",
)
DOCKERFILE = """FROM python:3.13-slim
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
RUN useradd --create-home --uid 1000 appuser
WORKDIR /home/appuser/app
COPY --chown=appuser requirements-baseline.txt requirements-web.txt ./
RUN python -m pip install --no-cache-dir -r requirements-web.txt
COPY --chown=appuser api.py retrieval.py DATA_SOURCES.md ./
COPY --chown=appuser web/ ./web/
COPY --chown=appuser models/ ./models/
COPY --chown=appuser data/medquad_revision.txt ./data/medquad_revision.txt
USER appuser
EXPOSE 8000
HEALTHCHECK --interval=30s --timeout=3s --start-period=30s --retries=3 CMD ["python", "-c", "import urllib.request; urllib.request.urlopen('http://127.0.0.1:8000/health', timeout=2).close()"]
CMD ["python", "-m", "uvicorn", "api:app", "--host", "0.0.0.0", "--port", "8000"]
"""
SPACE_README = """---
title: HealthQuery
emoji: 🔎
colorFrom: green
colorTo: blue
sdk: docker
app_port: 8000
pinned: false
---

# HealthQuery

Explore related English medical-information questions and archived sources.
This research demo combines an experimental question-type classifier with lexical retrieval.
It does not provide diagnoses or urgency assessments.

Source code: https://github.com/ryan30402/healthquery
Data attribution and limitations: [DATA_SOURCES.md](DATA_SOURCES.md).
The MedQuAD revision is recorded in `data/medquad_revision.txt`.
The source links and medical currency of the archived text have not been checked.
Use public example questions; do not enter personal health information.

The bundled joblib artifacts must be generated by the project owner from trusted code.
They require the same scikit-learn version pinned in `requirements-baseline.txt`.
`export_manifest.json` records SHA-256 hashes of the exported source and artifacts.
This export includes the prebuilt retrieval corpus but excludes raw XML and Git history.
"""
DOCKERIGNORE = ".git\n__pycache__\n*.pyc\n.cache\n"


def export_space(project_dir: Path, output_dir: Path) -> Path:
    project_dir = project_dir.resolve()
    output_dir = output_dir.expanduser().resolve()
    if output_dir.is_relative_to(project_dir):
        raise ValueError("Choose an output directory outside the project repository.")
    if output_dir.exists():
        raise FileExistsError(f"Output already exists; choose a new directory: {output_dir}")
    missing = [name for name in EXPORT_FILES if not (project_dir / name).is_file()]
    if missing:
        raise FileNotFoundError("Missing required files: " + ", ".join(missing))
    output_dir.mkdir(parents=True)
    try:
        for name in EXPORT_FILES:
            destination = output_dir / name
            destination.parent.mkdir(parents=True, exist_ok=True)
            shutil.copyfile(project_dir / name, destination)
        generated = {"Dockerfile": DOCKERFILE, "README.md": SPACE_README, ".dockerignore": DOCKERIGNORE}
        for name, contents in generated.items():
            (output_dir / name).write_text(contents, encoding="utf-8")
        hashes = {}
        for name in sorted((*EXPORT_FILES, *generated)):
            with (output_dir / name).open("rb") as handle:
                hashes[name] = hashlib.file_digest(handle, "sha256").hexdigest()
        manifest = {"format_version": 1, "file_sha256": hashes}
        (output_dir / "export_manifest.json").write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")
    except Exception:
        shutil.rmtree(output_dir)
        raise
    return output_dir


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, default=PROJECT_DIR.parent / "healthquery-space")
    args = parser.parse_args()
    output_dir = export_space(PROJECT_DIR, args.output)
    print(f"Exported deployment directory: {output_dir}")
    print("Nothing has been uploaded. Follow docs/DEPLOYMENT.md to build and publish it.")


if __name__ == "__main__":
    main()
